name: Test Secrets Configuration

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test VirusTotal API Key
        run: |
          if [ -n "${{ secrets.VIRUSTOTAL_API_KEY }}" ]; then
            echo "✅ VirusTotal API Key is configured"
          else
            echo "❌ VirusTotal API Key is missing"
            exit 1
          fi
      
      - name: Test Slack Bot Token
        run: |
          if [ -n "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
            echo "✅ Slack Bot Token is configured"
          else
            echo "❌ Slack Bot Token is missing"
            exit 1
          fi
      
      - name: Test Slack App Token
        run: |
          if [ -n "${{ secrets.SLACK_APP_TOKEN }}" ]; then
            echo "✅ Slack App Token is configured"
          else
            echo "❌ Slack App Token is missing"
            exit 1
          fi
      
      - name: Test Shodan API Key
        run: |
          if [ -n "${{ secrets.SHODAN_API_KEY }}" ]; then
            echo "✅ Shodan API Key is configured"
          else
            echo "❌ Shodan API Key is missing"
            exit 1
          fi
      
      - name: Test API Key Format
        run: |
          # Test VirusTotal API Key format (should be 64 characters)
          if [[ "${{ secrets.VIRUSTOTAL_API_KEY }}" =~ ^[a-f0-9]{64}$ ]]; then
            echo "✅ VirusTotal API Key format is valid"
          else
            echo "❌ VirusTotal API Key format is invalid"
            exit 1
          fi
          
          # Test Slack Bot Token format (should start with xoxb-)
          if [[ "${{ secrets.SLACK_BOT_TOKEN }}" =~ ^xoxb- ]]; then
            echo "✅ Slack Bot Token format is valid"
          else
            echo "❌ Slack Bot Token format is invalid"
            exit 1
          fi
          
          # Test Slack App Token format (should start with xapp-)
          if [[ "${{ secrets.SLACK_APP_TOKEN }}" =~ ^xapp- ]]; then
            echo "✅ Slack App Token format is valid"
          else
            echo "❌ Slack App Token format is invalid"
            exit 1
          fi
          
          # Test Shodan API Key format (should be 32 characters)
          if [[ "${{ secrets.SHODAN_API_KEY }}" =~ ^[a-zA-Z0-9]{32}$ ]]; then
            echo "✅ Shodan API Key format is valid"
          else
            echo "❌ Shodan API Key format is invalid"
            exit 1
          fi
      
      - name: Test API Connectivity
        run: |
          # Test VirusTotal API
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "x-apikey: ${{ secrets.VIRUSTOTAL_API_KEY }}" \
            "https://www.virustotal.com/api/v3/domains/example.com")
          if [ "$response" = "200" ]; then
            echo "✅ VirusTotal API is accessible"
          else
            echo "❌ VirusTotal API is not accessible (HTTP $response)"
            exit 1
          fi
          
          # Test Shodan API
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://api.shodan.io/api-info?key=${{ secrets.SHODAN_API_KEY }}")
          if [ "$response" = "200" ]; then
            echo "✅ Shodan API is accessible"
          else
            echo "❌ Shodan API is not accessible (HTTP $response)"
            exit 1
          fi 